# Generated by Django 4.0.5 on 2022-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_type',
            field=models.IntegerField(null=True),
        ),
    ]
