# Generated by Django 4.0.5 on 2022-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(choices=[('TVM', 'Thiruvananthapuram'), ('KLM', 'Kollam'), ('KTM', 'Kottayam'), ('MPM', 'Malappuram')], default='TVM', max_length=3),
        ),
    ]
