# Generated by Django 4.0.5 on 2022-07-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_no',
            new_name='phoneno',
        ),
    ]
