# Generated by Django 4.0.5 on 2022-07-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preq',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='preq',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
