# Generated by Django 4.0.5 on 2022-07-25 02:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verif',
            name='image',
            field=models.FileField(blank=True, upload_to=main.models.product_image_upload_handler),
        ),
    ]
