# Generated by Django 4.0.5 on 2022-07-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_preq_from_date_preq_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='preq',
            name='fromstring',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='preq',
            name='tostring',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
