# Generated by Django 4.0.5 on 2022-07-22 22:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_phone_no_user_phoneno_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preq',
            name='time',
            field=models.CharField(default=main.models.default_start_time, max_length=17),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_desc',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=90),
        ),
    ]
