# Generated by Django 4.0.5 on 2022-07-24 13:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_rating_count_alter_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrating',
            old_name='user',
            new_name='borrower',
        ),
        migrations.RenameField(
            model_name='productrating',
            old_name='val',
            new_name='len_rate',
        ),
        migrations.AddField(
            model_name='productrating',
            name='lender_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productrating',
            name='prod_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productrating',
            name='time',
            field=models.CharField(default=main.models.default_start_time, max_length=20),
        ),
        migrations.DeleteModel(
            name='LenderRating',
        ),
    ]
