# Generated by Django 4.0.5 on 2022-07-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_no',
            new_name='phoneno',
        ),
        migrations.AddField(
            model_name='user',
            name='u_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
