# Generated by Django 4.0.5 on 2022-07-24 17:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_user_productrating_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_image1',
            field=models.ImageField(blank=True, upload_to=main.models.product_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_image2',
            field=models.ImageField(blank=True, upload_to=main.models.product_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_image3',
            field=models.ImageField(blank=True, upload_to=main.models.product_image_upload_handler),
        ),
    ]
