# Generated by Django 4.0.5 on 2022-07-09 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_phone_no_user_phoneno_user_u_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_type',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_rate', models.IntegerField(default=0)),
                ('p_desc', models.CharField(max_length=70)),
                ('p_image1', models.ImageField(upload_to='uploads/')),
                ('p_image2', models.ImageField(blank=True, upload_to='uploads/')),
                ('p_image3', models.ImageField(blank=True, upload_to='uploads/')),
                ('month', models.DateField()),
                ('year', models.DateField()),
                ('status', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
