# Generated by Django 4.0.5 on 2022-07-22 22:58

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_preq_time_alter_product_p_desc_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preq',
            name='time',
            field=models.CharField(default=main.models.default_start_time, max_length=20),
        ),
    ]
