# Generated by Django 4.0.5 on 2022-07-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_rating_count_productrating_lenderrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderrating',
            name='val',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productrating',
            name='val',
            field=models.IntegerField(default=0),
        ),
    ]
