# Generated by Django 4.0.5 on 2022-07-24 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_p_image1_alter_product_p_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main.models.product_image_upload_handler)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.CharField(default=main.models.default_start_time, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
