# Generated by Django 4.0.5 on 2022-07-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
            ],
        ),
    ]
