# Generated by Django 4.0.5 on 2022-07-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_preq_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preq',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
