# Generated by Django 4.0.5 on 2022-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_verif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verif',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
