# Generated by Django 4.0.5 on 2022-07-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lenderrating_val_productrating_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerrating',
            name='val',
            field=models.IntegerField(default=0),
        ),
    ]
