# Generated by Django 4.0.5 on 2022-07-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_u_id_product_user_remove_product_p_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image1',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_image2',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_image3',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='ProdImage',
        ),
    ]
