# Generated by Django 4.0.5 on 2022-07-24 20:25

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_verif_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verif',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.product_image_upload_handler),
        ),
    ]
