# Generated by Django 4.0.5 on 2022-07-23 02:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.CharField(default=main.models.default_start_time, max_length=20),
        ),
    ]
