# Generated by Django 4.0.5 on 2022-07-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reportuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bor_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='len_rate',
            field=models.IntegerField(default=0),
        ),
    ]
